# Generated by Django 5.2.16 on 2026-08-02 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('benchmark', 'Benchmark dataset'), ('corpus', 'Real corpus'), ('integration', 'Integration validation')], default='benchmark', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=200)),
                ('filename', models.CharField(max_length=500)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('source_path', models.CharField(blank=True, max_length=1000)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workbench.collection')),
            ],
            options={
                'ordering': ['external_id'],
                'unique_together': {('collection', 'sha256')},
            },
        ),
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile', models.CharField(choices=[('standard-docling', 'Standard Docling (TableFormer)'), ('granite-table-crop', 'Granite Vision (crop)'), ('ground-truth', 'Ground truth')], max_length=50)),
                ('software_versions', models.JSONField(blank=True, default=dict)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('processing_seconds', models.FloatField(blank=True, null=True)),
                ('peak_vram_gib', models.FloatField(blank=True, null=True)),
                ('git_commit', models.CharField(blank=True, max_length=40)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='workbench.document')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('image_path', models.CharField(blank=True, max_length=1000)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='workbench.document')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('document', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='TableCandidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stable_table_id', models.CharField(db_index=True, max_length=100)),
                ('bbox', models.JSONField(blank=True, default=list)),
                ('crop_path', models.CharField(blank=True, max_length=1000)),
                ('ground_truth_path', models.CharField(blank=True, max_length=1000)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='workbench.document')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workbench.page')),
            ],
            options={
                'ordering': ['page', 'stable_table_id'],
                'unique_together': {('document', 'stable_table_id')},
            },
        ),
        migrations.CreateModel(
            name='TableExtraction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rows', models.PositiveIntegerField(default=0)),
                ('columns', models.PositiveIntegerField(default=0)),
                ('raw_otsl', models.TextField(blank=True)),
                ('raw_html', models.TextField(blank=True)),
                ('normalized_cells', models.JSONField(blank=True, default=list)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('artifact_paths', models.JSONField(blank=True, default=dict)),
                ('teds', models.FloatField(blank=True, null=True)),
                ('teds_s', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('missing', 'Missing')], default='success', max_length=20)),
                ('extraction_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='workbench.extractionrun')),
                ('table_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='workbench.tablecandidate')),
            ],
            options={
                'ordering': ['table_candidate'],
                'unique_together': {('table_candidate', 'extraction_run')},
            },
        ),
        migrations.CreateModel(
            name='ReviewTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_expert', 'Needs Expert'), ('skipped', 'Skipped')], default='unassigned', max_length=20)),
                ('priority', models.PositiveIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_tasks', to=settings.AUTH_USER_MODEL)),
                ('table_candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_task', to='workbench.tablecandidate')),
                ('candidate_x', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_tasks_as_x', to='workbench.tableextraction')),
                ('candidate_y', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_tasks_as_y', to='workbench.tableextraction')),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_x_score', models.PositiveIntegerField(default=0)),
                ('candidate_y_score', models.PositiveIntegerField(default=0)),
                ('preferred_result', models.CharField(choices=[('candidate_x', 'Candidate X'), ('candidate_y', 'Candidate Y'), ('equivalent', 'Equivalent'), ('neither', 'Neither')], max_length=20)),
                ('structure_errors', models.JSONField(blank=True, default=list)),
                ('text_errors', models.JSONField(blank=True, default=list)),
                ('comment', models.TextField(blank=True)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_reveal_comment', models.TextField(blank=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('review_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='workbench.reviewtask')),
                ('candidate_x', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews_as_x', to='workbench.tableextraction')),
                ('candidate_y', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews_as_y', to='workbench.tableextraction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('needs_review', 'Needs Review'), ('manual_correction', 'Manual Correction')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to=settings.AUTH_USER_MODEL)),
                ('table_candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='workbench.tablecandidate')),
                ('selected_extraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='workbench.tableextraction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
