# Generated by Django 5.2.16 on 2026-08-02 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingPreset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('description_short', models.CharField(blank=True, max_length=200)),
                ('profile_a_enabled', models.BooleanField(default=True)),
                ('profile_b_enabled', models.BooleanField(default=False)),
                ('generate_crops', models.BooleanField(default=False)),
                ('create_review_tasks', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('submitting', 'Submitting to processor'), ('processing', 'Processing'), ('importing', 'Importing results'), ('completed', 'Completed'), ('partial', 'Partially completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('external_job_id', models.CharField(blank=True, max_length=200)),
                ('processor', models.CharField(blank=True, max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('pages_processed', models.PositiveIntegerField(default=0)),
                ('tables_found', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_jobs', to=settings.AUTH_USER_MODEL)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_jobs', to='workbench.processingpreset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingArtifact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('page_image', 'Page image'), ('table_crop', 'Table crop image'), ('table_extraction', 'Table extraction result'), ('page_text', 'Page text'), ('layout_json', 'Layout detection JSON'), ('otsl', 'OTSL table markup')], max_length=30)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('region_id', models.CharField(blank=True, max_length=100)),
                ('file_path', models.CharField(blank=True, max_length=1000)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='workbench.processingjob')),
            ],
            options={
                'ordering': ['job', 'page_number', 'region_id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service account',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('token_prefix', models.CharField(max_length=8)),
                ('token_hash', models.CharField(db_index=True, max_length=128)),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='workbench.collection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
                ('service_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='workbench.serviceaccount')),
            ],
            options={
                'verbose_name': 'API token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('upload', 'User upload'), ('benchmark', 'Benchmark dataset'), ('api', 'API submission'), ('network_share', 'Network share'), ('batch_import', 'Batch import')], default='upload', max_length=20)),
                ('filename', models.CharField(max_length=500)),
                ('file_path', models.CharField(blank=True, max_length=1000)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='workbench.collection')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='processingjob',
            name='source_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='workbench.sourcedocument'),
        ),
        migrations.CreateModel(
            name='PageRegion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('region_type', models.CharField(choices=[('text', 'Text block'), ('title', 'Title / heading'), ('table', 'Table'), ('figure', 'Figure / image'), ('form', 'Form'), ('list', 'List'), ('header', 'Page header'), ('footer', 'Page footer'), ('other', 'Other')], max_length=20)),
                ('left', models.FloatField()),
                ('top', models.FloatField()),
                ('right', models.FloatField()),
                ('bottom', models.FloatField()),
                ('page_width', models.FloatField(blank=True, null=True)),
                ('page_height', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='workbench.processingjob')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='workbench.sourcedocument')),
            ],
            options={
                'ordering': ['source_document', 'page_number', 'top', 'left'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ui_language', models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], default='en', max_length=10)),
                ('timezone', models.CharField(default='Europe/Vienna', max_length=50)),
                ('guided_explanations', models.BooleanField(default=True)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User preferences',
                'verbose_name_plural': 'User preferences',
            },
        ),
    ]
