# Generated by Django 5.2.16 on 2026-08-03 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0008_region_correction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regioncorrection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='SearchPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_type', models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('region', 'Region'), ('table', 'Table'), ('table_row', 'Table row'), ('metadata', 'Metadata')], default='region', max_length=30)),
                ('archival_identifier', models.CharField(blank=True, max_length=255)),
                ('heading_context', models.CharField(blank=True, max_length=500)),
                ('text', models.TextField()),
                ('normalized_text', models.TextField(db_index=True)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_passages', to='workbench.page')),
                ('page_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_passages', to='workbench.pageregion')),
                ('processed_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_passages', to='workbench.document')),
                ('processing_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_passages', to='workbench.processingjob')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_passages', to='workbench.collection')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_passages', to='workbench.sourcedocument')),
            ],
            options={
                'ordering': ['page__page_number', 'ordinal', 'id'],
                'indexes': [models.Index(fields=['project', 'normalized_text'], name='workbench_s_project_dbb433_idx'), models.Index(fields=['source_document', 'processed_revision'], name='workbench_s_source__3e7e3e_idx')],
            },
        ),
    ]
