# Generated by Django 5.2.16 on 2026-08-03 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0009_alter_regioncorrection_id_searchpassage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('text', models.TextField(blank=True)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordinal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('search_enabled', models.BooleanField(default=False)),
                ('selected_revisions', models.JSONField(blank=True, default=list)),
                ('scope_snapshot', models.JSONField(blank=True, default=dict)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_threads', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='workbench.collection')),
                ('search_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_chat_threads', to='workbench.collection')),
                ('selected_sources', models.ManyToManyField(blank=True, related_name='chat_threads', to='workbench.sourcedocument')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChatRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('retrieving', 'Retrieving evidence'), ('assembling', 'Assembling context'), ('generating', 'Asking the model'), ('validating', 'Validating citations'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('status_message', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('worker_id', models.CharField(blank=True, max_length=200)),
                ('worker_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('retrieval_query', models.TextField(blank=True)),
                ('token_budget', models.PositiveIntegerField(default=12000)),
                ('source_tokens', models.PositiveIntegerField(default=0)),
                ('model_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('assistant_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_run', to='workbench.chatmessage')),
                ('user_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_runs', to='workbench.chatmessage')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='workbench.chatthread')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='workbench.chatthread'),
        ),
        migrations.AlterUniqueTogether(
            name='chatmessage',
            unique_together={('thread', 'ordinal')},
        ),
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('retrieval_method', models.CharField(blank=True, max_length=50)),
                ('selection_reason', models.CharField(blank=True, max_length=255)),
                ('score', models.FloatField(blank=True, null=True)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workbench.page')),
                ('page_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workbench.pageregion')),
                ('passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workbench.searchpassage')),
                ('processed_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workbench.document')),
                ('processing_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workbench.processingjob')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='workbench.chatrun')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workbench.sourcedocument')),
            ],
            options={
                'ordering': ['ordinal', 'id'],
                'unique_together': {('run', 'marker')},
            },
        ),
    ]
