# Generated by Django 5.2.16 on 2026-08-04 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0010_chatmessage_chatthread_chatrun_chatmessage_thread_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('worker_id', models.CharField(blank=True, max_length=200)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workbench.chatrun')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
