# Generated by Django 5.2.16 on 2026-08-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0011_chatrunevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrun',
            name='request_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
