# Generated by Django 5.2.16 on 2026-08-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0012_chatrun_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrun',
            name='error_code',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
