# Generated by Django 5.2 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("workbench", "0013_chatrun_error_code")]
    operations = [
        migrations.CreateModel(
            name="WorkerHeartbeat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("worker_id", models.CharField(max_length=200, unique=True)),
                ("last_seen", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-last_seen"]},
        ),
    ]
