# Generated by Django 5.2.16 on 2026-08-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0015_chat_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenceitem',
            name='page_text',
            field=models.TextField(blank=True),
        ),
    ]
