# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workbench", "0018_ocrrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processingartifact",
            name="artifact_type",
            field=models.CharField(
                choices=[
                    ("page_image", "Page image"),
                    ("table_crop", "Table crop image"),
                    ("table_extraction", "Table extraction result"),
                    ("page_text", "Page text"),
                    ("ocr_page", "Visual OCR page result"),
                    ("layout_json", "Layout detection JSON"),
                    ("otsl", "OTSL table markup"),
                ],
                max_length=30,
            ),
        ),
    ]
