# Generated by Django 5.2.16 on 2026-08-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0019_processingartifact_ocr_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='auto_retry_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='submission_retries',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
