# Generated by Django 5.2.16 on 2026-08-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0020_processingjob_submit_auto_retry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Force the user to set a new password before any other page.'),
        ),
    ]
