# Generated by Django 5.2.16 on 2026-08-11 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0023_workspace_recognition_prefs_and_revert_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regioncorrection',
            name='source_ocr_request',
            field=models.ForeignKey(blank=True, help_text='The recognition candidate that produced this correction, if any. Set once at acceptance time so a correction permanently retains its HTR/Vision provenance even after repeated accept/revert/re-accept cycles repoint the OcrRequest.accepted_correction shortcut.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_corrections', to='workbench.ocrrequest'),
        ),
    ]
